version: '3.9'

services:
  database:
    image: postgres:14-alpine
    container_name: sports_app_db
    env_file:
      - sports_app/.env
    ports:
      - '5432:5432'
    volumes:
      - sports_app-web-data:/var/lib/postgresql/data

volumes:
  sports_app-web-data: