# Generated by Django 4.2.6 on 2023-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
